### ISSUE TITLE
Stick to the chosen namespace + pick one if no image

### ISSUE THREAD

**Issue by Crocmagnon** [Quiq/docker-registry-ui#17]
I have a registry with token auth enabled but I'm unable to list images/tags. The UI shows "No data available in table", however the logs show that a token is correctly fetched and then when endpoints are targeted they respond with coherent data.

I tried to mount `/opt/data` as a folder and even make it writable by user `nobody` by adding the following lines to a custom Dockerfile :

```
USER root
RUN chown nobody:nogroup /opt/data
USER nobody
```

But I'm still unable to have a list of tags and I don't see any database file created. Do you have any idea what's going on ? Do you keep tags in a database ?

Thanks for the help ☺️

**Comment by Crocmagnon** [comment]
Nevermind, I didn't see the "Namespaces" dropdown. Suggestion : if there's only one namespace, select it by default, or present a list of namespaces before an empty list of repos 😊

**Comment by roman-vynar** [comment]
The default namespace is `library`, i.e. the root one. Probably, making a chosen namespace sticky will be better.

**Comment by roman-vynar** [comment]
In 0.7.3 I have made the following changes:
```
* Improve no data message on empty tables on UI.
* Show the root namespace "library" in the dropdown even when there are no repos in it.
```
Not making it sticky as it's complicated as it depends from an URL address, when going to / it should be the "library" root namespace and confuses things. You can always navigate to the namespace chosen from tags or tag info pages using the breadcrumb links instead of clicking Home.

If you have more suggestions, PR is welcome.
